Update tests
Signed-off-by: Igor Sukhih <igor@virtuozzo.com>

diff --git a/test/test-sparse b/test/test-sparse
--- a/test/test-sparse
+++ b/test/test-sparse
@@ -1,12 +1,9 @@
 #!/bin/bash
 
-set -e
+set -ex
 . ./functions
 
 V=2
-BLOCKSIZE=2048
-DELTA=100000
-SIZE=65536
 if [ -f /sys/module/ploop/parameters/large_disk_support ]; then
 	SIZENEW=60485760000
 else
@@ -28,32 +25,28 @@ done
 
 test_cleanup
 
-ploop init -s 1T -t none $TEST_IMAGE
-ploop mount -d /dev/ploop0 $TEST_DDXML
-dd if=/dev/urandom of=/dev/ploop0 bs=1M count=4 >/dev/null
-dd if=/dev/urandom of=/dev/ploop0 bs=1M count=1 seek=1022976  >/dev/null
-ploop umount $TEST_DDXML
-fallocate -p -o 1458176 -l 2097152 $TEST_IMAGE
-fallocate -p -o 5455872 -l 4096 $TEST_IMAGE
-fallocate -p -o 6291456 -l 4096 $TEST_IMAGE
-exit 0
-m1=`md5sum $TEST_IMAGE`
-ploop mount $TEST_DDXML
-ploop umount $TEST_DDXML
-m2=`md5sum $TEST_IMAGE`
-
-if [ "$m1" != "$m2" ]; then
-	echo "FAILED md5 mismatch $m1 != $m2"
-	exit 1
-fi
-
-ploop mount $TEST_DDXML
-ploop umount $TEST_DDXML
-m2=`md5sum $TEST_IMAGE`
-if [ "$m1" != "$m2" ]; then
-	echo "FAILED md5 mismatch $m1 != $m2"
-	exit 1
-fi
-exit 0
+ploop init -s 10G $TEST_IMAGE >>$TEST_LOG 2>&1
+dd if=/dev/zero of=$TEST_STORAGE/data bs=4K count=100 >>$TEST_LOG 2>&1
+dd if=/dev/urandom of=$TEST_STORAGE/data bs=4K count=100 seek=100 >>$TEST_LOG 2>&1
+ploop mount -d /dev/ploop0 -m $TEST_MNT $TEST_DDXML >>$TEST_LOG 2>&1
+for ((i=0; i<1000; i++)); do
+	dd if=$TEST_STORAGE/data of=$TEST_MNT/$i bs=1k >>$TEST_LOG 2>&1
+done
+ploop snapshot  $TEST_DDXML >>$TEST_LOG 2>&1
+ploop umount -d /dev/ploop0 -m $TEST_MNT $TEST_DDXML >>$TEST_LOG 2>&1
+tar --sparse -C / -cvf $TEST_STORAGE/data.tar ${TEST_IMAGE}* 
+rm -f ${TEST_IMAGE}*
+tar --sparse -C / -xvf $TEST_STORAGE/data.tar
+exit
+ploop mount -d /dev/ploop0 -m $TEST_MNT $TEST_DDXML >>$TEST_LOG 2>&1
+M1=`md5sum $TEST_STORAGE/data`
+for ((i=0 i<5000; i++)); do
+	M1_1=`md5sum $TEST_MNT/$i`
+	if [ "$M1" != "$M1_1" ]; then
+		echo "FAILED md5 mismatch $M1 != $M1_1"
+		exit 1
+	fi
+done
+ploop umount $TEST_DDXML >>$TEST_LOG 2>&1
 test_cleanup
-echo "FINISHED"
+echo "FINISHED [OK]"
